version: '3.7'
services:
  db:
    container_name: main-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  application:
    build: ./
    container_name: main-server
    command: npm run start:dev
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

